### ISSUE TITLE
Improvise the landing page

### ISSUE THREAD

**Issue by dwvicy** [dscrait/dscrait.tech#10]
1) Remove the colorful text on the landing page.
2) Update the content on the landing page.
3) Add a button "Apply Now" which would redirect to dscrait.tech/register

**Comment by mockingmoon** [comment]
Please assign this to me
P.S. First only these 3 tasks to done?

**Comment by dwvicy** [comment]
Have you read next.js documentation?

**Comment by mockingmoon** [comment]
Learning on the go . . .

**Comment by mockingmoon** [comment]
sent a pull request
couldn't commit due to husky message checking, so skipped that verification

**Comment by osmankbk** [comment]
Hello! Can I work on this?

**Comment by dwvicy** [comment]
@mockingmoon you're not supposed to work on an issue until it's assigned to you. Your PR won't be counted.

**Comment by mockingmoon** [comment]
> @mockingmoon you're not supposed to work on an issue until it's assigned to you. Your PR won't be counted.

Okayy
