### ISSUE TITLE
Embed medium publication site at dscrait.tech/blog

### ISSUE THREAD

**Issue by dwvicy** [dscrait/dscrait.tech#9]
1) @dwvicy would create the publication on medium
2) Just embed the publication landing page with top articles on dscrait.tech/blog

**Comment by dwvicy** [comment]
Refer this: https://medium.com/datadriveninvestor/embed-medium-as-a-blog-on-your-site-54a1b49cbe16
Our medium publication is this: https://medium.com/developer-student-club-rait

**Comment by dwvicy** [comment]
@evanessa234 is this in progress?

**Comment by evanessa234** [comment]
> @evanessa234 is this in progress?

yes!
